### ISSUE TITLE
PLugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Variatur/Qgeo#1]
#Problem

I see that there is another plugin QVeg which according to the code base might be the same. Is there any scope that these two plugins could be combined and then have an interface where users can choose the different layers because it looks to me as if the main difference is the type of layers which one plugin supports over the other

**Comment by GaryPattemore** [comment]
Hi @NyakudyaA ,
Thank you for taking the time to review my proposed plugin.
Qgeo was originally developed as part of Qveg and was derived directly from that code. I had intended Qgeo just to be a group within Qveg. Once I got into developing Qgeo I discovered that I needed to modify the code more than I had expected, to appropriately handle geoscience data and give the user what they would expect. I also realised that the name 'Qveg' and its stated purpose didn't closely align with geoscience data. So at that point I separated Qgeo from Qveg.
However, I don't have strong views on this either way - so happy to re-combine the two if it better satisfies QGIS plugin development guidelines.
Kind regards,
Gary.

**Comment by NyakudyaA** [comment]
> Hi @NyakudyaA ,
> Thank you for taking the time to review my proposed plugin.
> Qgeo was originally developed as part of Qveg and was derived directly from that code. I had intended Qgeo just to be a group within Qveg. Once I got into developing Qgeo I discovered that I needed to modify the code more than I had expected, to appropriately handle geoscience data and give the user what they would expect. I also realised that the name 'Qveg' and its stated purpose didn't closely align with geoscience data. So at that point I separated Qgeo from Qveg.
> However, I don't have strong views on this either way - so happy to re-combine the two if it better satisfies QGIS plugin development guidelines.
> Kind regards,
> Gary.

There are no not really any guidelines with regards to this, however as I had seen that the code base is the same I thought it would make sense to have them as one but I am happy with your explanation.

**Comment by GaryPattemore** [comment]
Thanks @NyakudyaA - your input on this is much appreciated. Regards, Gary.
